#!/bin/bash

verbose_mode="false"


check_root() {
    if [[ "${UID}" -ne 0 ]]; then
        die "Please run this program as a root!"
    fi
}

check_root


__change_main_torrc() {

    grep -q -x 'User tor' /etc/tor/torrc || echo 'User tor' >> /etc/tor/torrc

    grep -q -x 'SocksPort 9050 IsolateClientAddr IsolateClientProtocol IsolateDestAddr' /etc/tor/torrc || echo 'SocksPort 9050 IsolateClientAddr IsolateClientProtocol IsolateDestAddr' >> /etc/tor/torrc

    grep -q -x 'DNSPort' /etc/tor/torrc || echo 'DNSPort 53' >> /etc/tor/torrc

    grep -q -x 'TransPort 9040 IsolateClientAddr IsolateClientProtocol IsolateDestAddr' /etc/tor/torrc || echo 'TransPort 9040 IsolateClientAddr IsolateClientProtocol IsolateDestAddr' >> /etc/tor/torrc

    grep -q -x 'ExcludeNodes {es},{us},{ca},{de},{gb},{au},{nz},{dk},{fr},{nl},{no},{be},{it},{sw},{??} StrictNodes 1' /etc/tor/torrc || echo 'ExcludeNodes {es},{us},{ca},{de},{gb},{au},{nz},{dk},{fr},{nl},{no},{be},{it},{sw},{??} StrictNodes 1' >> /etc/tor/torrc

    grep -q -x 'ControlPort 8040' /etc/tor/torrc || echo 'ControlPort 8040' >> /etc/tor/torrc

    grep -q -x 'Sandbox 1' /etc/tor/torrc || echo 'Sandbox 1' >> /etc/tor/torrc

    grep -q -x 'ClientUseIPv4' /etc/tor/torrc || echo 'ClientUseIPv4' >> /etc/tor/torrc

    grep -q -x 'NewCircuitPeriod 5' /etc/tor/torrc || echo 'NewCircuitPeriod 5' >> /etc/tor/torrc

}


function __main__() {

  # Stores the current date.
  readonly _cdate=$(date +%Y%m%d)
  readonly _tor_hashpass="$(tor --hash-password "$(date +%Y%m%d && echo $(( $RANDOM % 100000000 + 1 )))" | tail -1)"
  # Variables related to the log file. Divided into three parts due
  # to the better possibility of manipulation for the user.
  # shellcheck disable=SC2154
  readonly _log_directory="/var/log"
  # shellcheck disable=SC2154
  readonly _log_file="firevigeo-prepare.${_cdate}.log"
  readonly _log_stdout="${_log_directory}/firevigeo-prepare.stdout.log"
  readonly _log_path="${_log_directory}/${_log_file}"
  readonly _torrc_config=/etc/tor/torrc

  for number in {9000..9010}
    do
    echo "Tor socks: $number "
    cp /etc/tor/torrc /etc/tor/torrc.$number

    sed -i 's/SocksPort 9050/SocksPort $number/g' torrc.$number
    sed -i 's/TransPort 9040/TransPort `expr $number + 800`/g' torrc.$number
    sed -i 's/ControlPort 9050/ControlPort `expr $number + 1000`/g' torrc.$number

    ln -s data/config/tor@.service /usr/lib/systemd/system/tor@$number.service

    echo "HashedControlPassword $_tor_hashpass" >> torrc.$number

    systemctl start tor@$number.service

        if [[ $_kstate -ne 0 ]]; then
	    echo Done!
            continue
	else
	   echo Failed!
	   exit
        fi

  done

echo "Hashed password is: $_tor_hashpass"

#        "value is less or equal 1023"


#        _sprintf "stop" "value is equal or grather then 65536"

}


own_params() {

  eval set -- "$_GETOPT_PARAMS"
  while true ; do

    case $1 in

      --help)

        _help_

        shift ; _exit_ "0" ;;

      --debug)

        export stdout_mode="debug"

        shift ;;

      --verbose)

        export verbose_mode="true"

        shift ;;

      -i|--init)

        export init_state="1"

        export init_number="${2}"

        shift 2 ;;

      -k|--kill)

        export kill_state="1"

        export kill_status="0"

        shift ;;

      -s|--show-id)

        export show_id_state="1"

        shift ;;

      -n|--new-id)


        export new_id_state="1"

        shift ;;

      -u|--user)

        export user_state="1"

        export user_name="${2}"

        shift 2 ;;

      --socks-port)

        export socks_port_state=1

        export socks_port_number="${2}"

        shift 2 ;;

      --control-port)

        export control_port_state=1

        export control_port_number="${2}"

        shift 2 ;;

      --proxy)

        export proxy_state=1

        export proxy_type="${2}"

        shift 2 ;;

      --haproxy)

        export frontend_state=1

        export frontend_type="haproxy"

        shift 2 ;;

      *)

        if [[ "$2" == "-" ]] || [[ ! -z "$2" ]] ; then

          printf "%s: invalid option -- '%s'\\n" "$_init_name" "$2"
          _exit_ "1"


        # elif [[ -z "$2" ]] ; then break ; fi
        else break ; fi

        ;;

    esac

  done
}


__main__
__change_main_torrc
